name: HolaMundo

on: 
  push: 
    branches:
       - main
       - develop
       - releases
       - hotfix

jobs:
  Saludos:
    runs-on: ubuntu-latest

    steps:
      - name: descargar el repo
        uses: actions/checkout@v2

      - name: Hola Push
        run: echo "hola mundo desde github actions on push"
