name: HolaMundo

on: 
  push: 
    branches:
       - main
       - develop
       - releases
       - hotfix

jobs:
  Saludos:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Repo
        uses: actions/checkout@v4

      - name: Hola Push
        run: echo "hola mundo desde push"

      - name: Hola Develop
        if: ${{github.ref == 'refs/heads/develop'}}
        run: echo "hola mundo desde develop"
        
      - name: Hola Main
        if: ${{github.ref == 'refs/heads/main'}}
        run: echo "hola mundo desde main"
